version: 1
runtime: python27
api_version: 1
application: bookyrself
threadsafe: true


handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: guestbook.app



libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

